package org.damianw.huehuehue.api.model

/**
 * @author Damian Wieczorek {@literal <damian@farmlogs.com>}
 * @since 7/14/15
 * (C) 2015 Damian Wieczorek
 */
enum class Error(val code: Int) {
  UNAUTHORIZED(1),
  RESOURCE_UNAVAILABLE(2),
  UNSUITABLE_METHOD(3),
  MISSING_PARAMETERS(4),
  PARAMETER_UNAVAILABLE(5),
  INVALID_VALUE(6),
  IMMUTABLE_PARAMETER(7),
  TOO_MANY_ITEMS(8),
  REQUIRES_PORTAL(12),
  INTERNAL(901),
  LINK_BUTTON_NOT_PRESSED(101),
  DHCP_CANNOT_BE_DISABLED(110),
  INVALID_UPDATE_STATE(111),
  NOT_CURRENTLY_MUTABLE(201),
  TOO_MANY_GROUPS(301),
  DEVICE_UNREACHABLE(304),
  IMMUTABLE_GROUP_TYPE(305),
  SCENE_BUFFER_FULL(402),
  FORBIDDEN_SENSOR_TYPE(501),
  SENSOR_LIST_FULL(502),
  RULE_ENGINE_FULL(601),
  CONDITION_ERROR(607),
  ACTION_ERROR(608),
  UNABLE_TO_ACTIVATE(609),
  SCHEDULE_LIST_FULL(701),
  INVALID_TIME_ZONE(702),
  CANNOT_SET_BOTH_TIME_AND_TIME_ZONE(703),
  CANNOT_CREATE_SCHEDULE(704),
  TIME_IN_PAST(705);
  companion object: Map<Int, Error> by values().toMap({ it.code })
}
